manifest:
  version: "0.13"

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zmkfirmware/zephyr

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.5.0+zmk-fixes
      import: west.yml

  self:
    path: config
